version: "3"
services:
  deltrack:
    build:
      context: ./DelTrack
      dockerfile: Dockerfile
    container_name: DelTrack
    restart: unless-stopped
    environment:
      MONGO_STRING: ${MONGO_STRING}
      SESSION_SECRET: ${SESSION_SECRET}
      EMAIL_SERVER_NAME: ${EMAIL_SERVER_NAME}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_NAME: ${EMAIL_NAME}
      NOTIFY_EMAIL: ${NOTIFY_EMAIL}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - deltrack-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.deltrack.rule=Host(`deltrack.jeffresc.dev`)
      - traefik.http.routers.deltrack.tls=true
      - traefik.http.routers.deltrack.tls.certresolver=le
      - traefik.http.services.deltrack.loadbalancer.server.port=3000
  mongo:
      image: mongo:latest
      container_name: DelTrack-Mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      networks:
        - deltrack-backend

networks:
  deltrack-backend:
    driver: bridge
